### ISSUE TITLE
what happen on my file and folder color?

### ISSUE THREAD

**Issue by pongib** [jesseweed/seti-ui#185]
I have something wrong with my color folder. 

![capture](https://cloud.githubusercontent.com/assets/9392677/8597535/3265ab98-2680-11e5-9321-4387a7d4636e.JPG)

Any suggest? it happen on my win 8.1 and mac also, By the way, Your theme is awesome.

**Comment by asiahoe** [comment]
@pongib Atom features many [Git integrations](http://blog.atom.io/2014/03/13/git-integration.html). The colors you see in your treeview (where files and folders are listed) reflects the current git status of the file.

* White is the default color and indicates a file that has not been changed since your last commit.
* Green indicates a newly added file.
* Yellow indicates a file that has been modified.
* Grey files are ignored in the .gitignore file.
* Red files have been removed. (Once this change is committed, they disappear from the treeview.)

Many of us don't like the fact that the Seti-UI icons change in addition to the filename. @jesseweed has indicated that he is considering it for a future release. You can see [issue 79](https://github.com/jesseweed/seti-ui/issues/79) for more information.

If that answers your question, please remember to close this issue! Thanks. :grin:

**Comment by pongib** [comment]
@asiahoe, Thank you for enlighten me.
