### ISSUE TITLE
No Color Scheme?

### ISSUE THREAD

**Issue by aufa** [jesseweed/seti-ui#209]
After Update SetiUI (sublime text3 ) no color scheme provide
and folder Fold Icon not shown on sidebar?
is Seti UI has been remove color scheme?

**Comment by dgo721** [comment]
Same here, I have to install the package manually to get the theme back but still, color_scheme is still missing. Any of the previews releases has it?

**Comment by marefr** [comment]
Same problem for me, on Windows at least.

**Comment by dgo721** [comment]
Seems that this issue is being covered [right here](https://github.com/ctf0/Seti_ST3/issues/207), since this the actual port working in Sublime Text. You can actually download the schemes as well.

**Comment by aufa** [comment]
update make seti UI inconsistent and very very often update

**Comment by ctf0** [comment]
@aufa ur issue is related to the ST port not the original ATOM package,
secondly it keeps updating because PackageControl changed the way they pull the update from the repo, so now any new change i add gets pushed to the user immediately, i fixed that but am still waiting for PC to merge the changes.

**Comment by jesseweed** [comment]
Closing this out since it's a Sublime issue. If you still have trouble, you can file another bug on this repo: https://github.com/ctf0/Seti_ST3
