### ISSUE TITLE
Can't click scrollbar thumb

### ISSUE THREAD

**Issue by timdp** [jesseweed/seti-ui#243]
In the tree view, I can only scroll with the scroll wheel. The vertical scrollbar thumb gives me a horizontal resize cursor and only allows me to resize the tree view sidebar.

Windows 10, Atom 1.7.3, Seti 1.0.3.

**Comment by cwilli34** [comment]
I have this same issue on Linux.  I can't grab the tree-view scrollbar.

**Comment by jesseweed** [comment]
Hmm, I can't repro on Mac (and I don't think I made any changes to the scroll bar). I'll see if I can get into Windows or Linux and to to repro.

**Comment by cwilli34** [comment]
This was an issue for me before the new update.

**Comment by jesseweed** [comment]
@cwilli34 does it happen only with this theme?

**Comment by cwilli34** [comment]
It does not happen with any of the core themes.  My scrollbars are thin because of the linux distro I use, but I am still able to grab them in all the core themes.  I cannot grab the scrollbar at all in the treeview with seti-ui, and I can barely do it in the code syntax section if I have split panes.  It tries to grab the edge of the pane first to resize and I really have to focus to get it to grab the scrollbar (probably like a pixel wide section next to the scrollbar actually allows me to grab the scrollbar).

Image of only being able to grab and resize when hovering over scrollbar in seti-ui:
![screenshot_20160503_103615](https://cloud.githubusercontent.com/assets/9610352/14986694/fdde0434-111a-11e6-8e7b-94a2a6d18aa8.png)

In Atom Dark it actually allows you to hover over the scrollbar without resize:
![screenshot_20160503_103909](https://cloud.githubusercontent.com/assets/9610352/14986789/4de61ae8-111b-11e6-9652-e8d382f51f3c.png)

**Comment by thequailman** [comment]
I was able to fix this by adding this to the stylesheet:

.tree-view-resizer {
  padding-right: 5px;
}

**Comment by cwilli34** [comment]
Yes, I am not sure which stylesheet is the correct one, but when I add it to the index.less style sheet @thequailman's fix works.  A little bit more padding on the other scrollbars would probably be helpful too.

**Comment by jesseweed** [comment]
Cool, thanks for the debugging guys, I'll take a look at getting a fix in.

**Comment by The-Pingu** [comment]
I have the same problem that the scrollbar is too small to grab.
I don't know in which stylesheet to put the fix from @mikemcrill. Can someone give me a hint? :)

**Comment by jesseweed** [comment]
Hey guys, so it seems no matter what I do I can't make any change to the scrollbars on Mac. I went ahead though and just copied in the scrollbar styles from Atom Material since report is those work ok. It still all looks the same to me though. So let me know if that makes it any better or not once you update to 1.3. Thanks!

**Comment by The-Pingu** [comment]
Thanks, that's a nice big scrollbar :+1: 
(I'm on Ubuntu)

**Comment by jesseweed** [comment]
Cool! I'll look at adding scrollbar size to config next time around.

**Comment by jesseweed** [comment]
I believe this should have been fixed a few updates back. Feel free to re-open if you still find you have issues. Thanks!
