### ISSUE TITLE
Issues with file picker modal

### ISSUE THREAD

**Issue by Leeds-eBooks** [jesseweed/seti-ui#259]
<img width="499" alt="screen shot 2016-05-03 at 14 16 39" src="https://cloud.githubusercontent.com/assets/4380655/14984296/d725e5cc-1139-11e6-9f97-bab1c1487de3.png">

A few issues here:

1. With a dark UI, I would expect the text input to be dark. This bright box is quite painful to look at. The previous version of Seti-UI I'm pretty sure had a dark background here.
2. The git "modified" icon to the left of the first file in the list, `actions.js`, is in the wrong place, ideally it would be on the right. I think this is from an atom core package.
3. When the file path is long, it gets pushed below the filename.
4. I am using icons from the `file-icons` package, they are cut off at the bottom (this is particularly noticeable in the `.json` icon).

**Comment by jesseweed** [comment]
1. I made the white input deliberately to draw focus to it, and because I kind of like the contrast, but I can see the point about it maybe standing out too much, I'll consider adjusting the color.

2. That's a good catch, I'll see about moving it to the right.

3. Cool, I'll look at moving to the right.

4. Seti and file icons package generally don't play very nicely together as seti is designed around very specific icons. Disabling custom icons should fix conflicts for tabs and the side-bar, but I didn't realize file-icons was adding icons to file picker modal now as well. I'll have to add that to the list.

**Comment by Leeds-eBooks** [comment]
Great, thanks. Even just a slightly less bright white would make a world of difference. I also like the contrast, but in a dark room it genuinely does hurt a little!

**Comment by jesseweed** [comment]
This should be fixed in 1.2 update. Feel free to re-open if you still have an issue.
