### ISSUE TITLE
Scrollbar is 1 pixel to the left

### ISSUE THREAD

**Issue by PedroGabriel** [jesseweed/seti-ui#348]
I really tried to fix it but I don't understand exactly why it is 1 px to the left. Tried some things but nothing worked. Anyone has this problem? Really hard to click on it when rushing

![Bug picture](http://i.imgur.com/ggQXYvh.png)

**Comment by jesseweed** [comment]
@PedroGabriel I made some scrollbar adjustments in the recent 1.4 release. Can you see if that addresses your issue?

**Comment by PedroGabriel** [comment]
@jesseweed Just updated Atom and your theme, it still 1px to the left. Also disabled every extenstion/package to make sure there was nothing doing it. When using default atom theme it works so it could be a problem with seti-ui.

Not sure if I'm the only one having this problem or the only one caring about it 😛

**Comment by NNeto** [comment]
I'm using the version 1.9 and I'm not sure if this is related to the theme or Atom itself, but I've just simply removed this "atom-panel-container" as a fast workaround. I don't know what issues making it entirely  "display: none" might cause, but having to actively aim to the scrollbar instead of just throwing the pointer to the right most edge of the screen was really annoying, especially with touchpad.

**Comment by NNeto** [comment]
The problem is specifically related to the border-left on the "atom-panel-container" with class "right" in addition to the "min-width: 1px" on the div with classes "atom-dock-inner right" inside of it. Dealing with those instead of the "display: none" overkill keep us able of using the right panel. Although it's necessary to use key shortcut to open the panel since you lose the arrow icon that shows up when the pointer hover over the edge.

**Comment by jesseweed** [comment]
I believe this issue has been resolved, feel free to reopen if not
