### ISSUE TITLE
i can't update seti ui

### ISSUE THREAD

**Issue by ibrahim69** [jesseweed/seti-ui#381]
i can't update it and i can't remove it

**Comment by pgrantmartello** [comment]
Just delete the package from your .atom folder and then reinstall.

**Comment by ngbravo** [comment]
Deleting this does not solve the problem. I believe the problem is not with seti-ui, but with seti-syntax: https://github.com/jesseweed/seti-syntax/issues/145, which is already being addressed

Therefore I think this issue should be closed.

**Comment by jesseweed** [comment]
I believe this has been fixed. Feel free to re-open if you still experience this issue.

**Comment by faddah** [comment]
Hello,

Can this please re-opened, @jesseweed, please? I am seeing the exact same thing with both `seti-ui` and `seti-syntax` installed, and I especially like using `seti-syntax`. 

my set-up is:

Mac OS v10.12.4
Atom v1.16.0

and from `apm version` on the command line —

```
$ apm --version
apm  1.16.1
npm  3.10.5
node 6.9.5 x64
python 2.7.10
git 2.11.0
```
`
with `seti-ui` and `seti-syntax` installed, either from within Atom > Settings > Updates or from the command line with `apm update`, i get —

```
$ apm update
undefined
```

... everytime. the moment i remove seti-ui` and `seti-syntax`, updates, both from within the Atom editor app and from the command line, work fine.

can this please be updated so that all your seti theme packages work with the apm update in the current Atom 1.16.0, please?

i will also put this over in jjesseweed/seti-syntax#145 , which is the same issue for seti-syntax.

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by faddah** [comment]
@jesseweed et al. —

ok, I see what was happening here and got some suggestion over at jesseweed/seti-syntax#145, which had the same issue. 

i did what they suggested and updates are working for me now, with the new seti-ui@1.7.0 & seti-syntax@1.1.3 running now and, after restart, Atom editor updates working fine. so ok to leave it closed, but I would suggest adding to your README.md with notes that if they had the earlier versions and are running into the update problem —

1. delete old versions of seti-ui & seti-syntax from Atom themes
2. restart Atom
3. install the latest seti-ui@1.7.0 & seti-syntax@1.1.3 in Atom > Settings > Install
4. restart Atom & test Atom > Settings > Updates to make sure it working o.k.

That is my suggestion for the README.md here. I also posted this in jesseweed/seti-syntax#145. ok to keep this closed, otherwise.

best,

— faddah
portland, oregon, u.s.a.
