### ISSUE TITLE
Icon for Puppet

### ISSUE THREAD

**Issue by dhollinger** [jesseweed/seti-ui#65]
Would like a sidebar icon for puppet files (.pp)

Icon that is used in the Sublime Text Seti UI would be perfect:

![](https://raw.githubusercontent.com/ctf0/Seti_ST3/master/icons/file_type_puppet.png)
![](https://raw.githubusercontent.com/ctf0/Seti_ST3/master/icons/file_type_puppet%402x.png)

Thanks!

**Comment by Equilibri0** [comment]
:+1:  , i like the idea

**Comment by dhollinger** [comment]
Any update on adding a Puppet icon for .pp files?

**Comment by Alhadis** [comment]
@dhollinger Do you know if that's the same "Puppet" as [this](https://puppet.com/)?

The icon differs drastically from the logo; I'm asking because I added the latter one to the File Icons package [fairly recently](https://github.com/DanBrooker/file-icons/releases/tag/v1.7.8#new-icons), and now I'm wondering if I used the right one. :S I know absolutely *nothing* about Puppet, so... wouldn't mind being enlightened. =)

**Comment by dhollinger** [comment]
@Alhadis it is. They changed their logo last month, so the icon I provided is no longer the official logo/icon anymore.

**Comment by Alhadis** [comment]
Ah, damn. :\ Sorry to hear that.

You or @jesseweed are welcome to update the icon using the [logo I traced](https://github.com/DanBrooker/file-icons/releases/download/v1.7.8/Icon-SVGs-v1.7.8.zip). =) You'll find it in the zipped SVG folder.

**Comment by dhollinger** [comment]
I'd love to, but I'll leave it to @jesseweed.

I tried updating it a few weeks ago and I don't appear to have the knowledge or tools to do so..... and not much time to learn either. Not a top priority for me at the moment.

Also important to note that the color of their logo changed from purple to a dark yellow. See www.puppet.com
